version: '3'

services:
  registry:
    image: registry:2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - registry_credentials:/etc/docker/registry/auth:ro
    networks:
      - registry-net

networks:
  registry-net:
    external: true

volumes:
  registry_data:
    external: true
  registry_credentials:
    external: true
