version: "2.1"
services:
  app:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.83 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - netboot_config:/config # optional
      - netboot_assets:/assets # optional
    ports:
      - 3000:3000 # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 9000:80 # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
    networks:
      - netboot_network

networks:
  netboot_network:
    external: true

volumes:
  netboot_assets:
    external: true
  netboot_config:
    external: true