version: '3'
services:
  app:
    image: atuin/atuin:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ATUIN_DB_HOST=atuin-db
      - ATUIN_DB_USER=atuin
      - ATUIN_DB_PASSWORD=atuin
      - ATUIN_DB_NAME=atuin
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - atuin-db

  db:
    image: postgres:13
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=atuin
      - POSTGRES_PASSWORD=atuin
      - POSTGRES_DB=atuin
    volumes:
      - atuin_db_volume:/var/lib/postgresql/data

volumes:
  atuin_db_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,rw
      device: :/mnt/nfs/atuin-db-data
