version: '3'
services:
  app:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    environment:
      - TZ=Europe/Warsaw

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/redis-data

networks:
  redis_network:
    external: true
